// Copyright © 2026 Marcel Joachim Kloubert <marcel@kloubert.dev>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

import type { EnvVariable } from '@/types';

/**
 * Escapes a value for use in a .env file.
 * Wraps value in quotes if it contains special characters.
 */
function escapeEnvValue(value: string): string {
  // If value contains spaces, newlines, quotes, or special characters, wrap in quotes
  if (/[\s"'`$\\]/.test(value) || value.includes('#')) {
    // Escape backslashes and double quotes
    const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    return `"${escaped}"`;
  }
  return value;
}

/**
 * Validates an environment variable key.
 */
function isValidEnvKey(key: string): boolean {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(key);
}

/**
 * Generate .env file content from environment variables.
 * Filters out invalid keys and empty entries.
 */
export function generateEnvFileContent(variables: EnvVariable[] | undefined): string {
  const lines: string[] = [
    '# Environment variables for Claude Code Docker container',
    '# Generated by Claude Initializr',
    '',
  ];

  const validVariables = (variables ?? []).filter(
    (v) => v.key && isValidEnvKey(v.key)
  );

  // Track seen keys to handle duplicates (last one wins)
  const seenKeys = new Set<string>();
  const uniqueVariables = [...validVariables].reverse().filter((v) => {
    if (seenKeys.has(v.key)) {
      return false;
    }
    seenKeys.add(v.key);
    return true;
  }).reverse();

  for (const variable of uniqueVariables) {
    const escapedValue = escapeEnvValue(variable.value);
    lines.push(`${variable.key}=${escapedValue}`);
  }

  // Add trailing newline
  lines.push('');

  return lines.join('\n');
}
